### PR TITLE
Decouple jackson-databind (includes OciFunction, OciFunctionFeature, OracleCloudMetadataResolver).

### LINKED ISSUE #603: OciFunction is coupled to Jackson ObjectMapper
### Issue description

https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/oraclecloud-function/src/main/java/io/micronaut/oraclecloud/function/OciFunction.java#L78

### PR DESCRIPTION
**Pull request by wetted**
closes #603

### CODE REVIEW

**Comment by wetted** [comment]
I'm sort of shooting from the hip on my changes to `OciFunctionFeature`. The one to `OciFunction` seems more straightforward. Happy to learn if I got it wrong.

**Comment by graemerocher** [comment]
think this will break the function support and I am not sure we can decouple it from Jackson in the short term.

**Comment by n0tl3ss** [comment]
I think https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/604 this decouples it from `micronaut-jackson-databind` but other modules would bring jackson.

**Comment by wetted** [comment]
@sdelamo it seems to me we should abandon and close this PR and the original issue, yes?

**Pull request closed without merging**
