### PR TITLE
Allow retry on closed channel

### PR DESCRIPTION
**Pull request by yawkat**
In NettyHttpClient#isProcessingException, return true for PrematureChannelClosureException. This lets the client retry the request for that exception.

Also had to make a few changes to make ManagedNettyHttpProvider work in the bootstrap context.

### CODE REVIEW

**Comment by yawkat** [comment]
re testing: The bootstrap context changes are covered by OracleCloudVaultConfigurationClientSpec. The closed channel change is covered by OracleCloudVaultConfigurationClientSpec if the vault has enough secrets, not sure if that's the case with the tests we run on github actions.

**Comment by graemerocher** [comment]
@n0tl3ss setup 1000s of secrets so if this passes it should be good. @n0tl3ss can you confirm?

**Comment by n0tl3ss** [comment]
> @n0tl3ss setup 1000s of secrets so if this passes it should be good. @n0tl3ss can you confirm?

I have created 1000 secrets on the `phx` region, I am not sure which region is used on CI. 
This workflow are testing this: https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/.github/workflows/graalvm-oci.yml and its run only on release/master branch.

To be sure I will create 1000 more on the `us-ashburn-1` region. I will notify you when its done.

**Comment by n0tl3ss** [comment]
Everything is ready @graemerocher @yawkat. 🤞

**Comment by yawkat** [comment]
thanks!

**Comment by graemerocher** [comment]
@yawkat @n0tl3ss do we need to rerun CI to check for sure?

**Comment by yawkat** [comment]
@graemerocher just reran it and it passed

**Comment by yawkat** [comment]
hm actually doesnt seem it's run as part of "Java CI / build (17) (pull_request)". but either way i ran it locally and it passed.

**Comment by graemerocher** [comment]
@n0tl3ss do you know why it isn't run?

**Comment by n0tl3ss** [comment]
> @n0tl3ss do you know why it isn't run?

As mention before https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/.github/workflows/graalvm-oci.yml is running only on master and release branches.

**Comment by n0tl3ss** [comment]
@yawkat can you push again some dummy commit to trigger the build. I have enabled workflow again.

**Review by n0tl3ss — APPROVED** [review]

**Pull request merged**
