### PR TITLE
OCI SDK 3 compatibility, add netty-based OCI http client

### LINKED ISSUE #434: Upgrade to Oracle Cloud SDK v3
### Feature description

We should upgrade to Oracle Cloud SDK v3 and provide a Netty HTTP transport

### PR DESCRIPTION
**Pull request by yawkat**
This PR adds compatibility with OCI SDK 3.0.0. The changes for compatibility are minor. We can't upgrade to OCI SDK 3 until Micronaut 4, but this change will let users upgrade their SDK if manually.

Additionally, this PR adds an early netty-based implementation of the new OCI SDK 3 HTTP client abstraction. This avoids the dependency on jersey.

The client uses netty directly, instead of the micronaut HTTP client, because OCI is fairly particular when it comes to how the requests are structured.

In its current state, the client works. It's one of the implementations I used for testing when I designed the OCI SDK HTTP client abstraction (this is also why the tests are junit, not spock). Some features are still missing (e.g. trust store configuration), and there is still room for performance improvements (mostly connection pooling).

Fixes #434

### CODE REVIEW

**Comment by yawkat** [comment]
@melix how can i get the japicmp to pass? it doesn't like the new module apparently

**Comment by melix** [comment]
in the new module build file, use:

```
micronautBuild {
    binaryCompatibility.enabled = false
}
```

which would have to be reverted after the 1st release

**Comment by yawkat** [comment]
thanks!

**Comment by graemerocher** [comment]
@yawkat I would like to get all the other modules in this project updated to OCI SDK v3 and the tests running with the new client before merging

**Comment by graemerocher** [comment]
Also if you can address the sonar issues that would be great https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/436/checks?check_run_id=9415702248

**Comment by yawkat** [comment]
@graemerocher i tested the other modules, with these changes they just work if you bump the version number and add the jersey httpclient dependency. but, need to do that on the 3.0.x branch, not on master.

**Comment by graemerocher** [comment]
right but we need them working with the netty client

**Comment by yawkat** [comment]
i think that should just work as well, i will test it

**Comment by yawkat** [comment]
yea it does, the diff is

```diff
Index: oraclecloud-common/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/oraclecloud-common/build.gradle b/oraclecloud-common/build.gradle
--- a/oraclecloud-common/build.gradle	(revision df75834bbd89b8de7a07129563045ef4fc16d0f2)
+++ b/oraclecloud-common/build.gradle	(date 1668095655456)
@@ -6,6 +6,7 @@
     api(libs.oci.common) {
         exclude group: 'org.javassist', module: 'javassist'
     }
+    implementation projects.oraclecloudHttpclientNetty
     api mn.micronaut.inject
     compileOnly mn.graal
     compileOnly mn.micronaut.runtime
Index: gradle.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/gradle.properties b/gradle.properties
--- a/gradle.properties	(revision df75834bbd89b8de7a07129563045ef4fc16d0f2)
+++ b/gradle.properties	(date 1668095592924)
@@ -7,7 +7,7 @@
 spockVersion=2.1-groovy-3.0
 
 fnVersion=1.0.150
-ociVersion=2.41.0
+ociVersion=3.0.0
 oci3Version=3.0.0
 ojdbcVersion=21.6.0.0.1
```

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
