### PR TITLE
Add block detection to httpclient-netty

### PR DESCRIPTION
**Pull request by yawkat**
Pending https://github.com/micronaut-projects/micronaut-core/pull/10743

### CODE REVIEW

**Comment by yawkat** [comment]
in particular this will detect the case where the calling thread is also the thread that the client wants to use. this will 100% lead to a deadlock because the client needs to wait for the event loop to be available, but the event loop is blocked waiting for the client. There are no valid use cases for this and it will always deadlock.

This is *not* a general detection like https://github.com/micronaut-projects/micronaut-core/pull/10010

**Comment by graemerocher** [comment]
seems to be failing tests or something

**Comment by yawkat** [comment]
it breaks because the core pr isnt released yet so it doesnt compile

**Review by andriy-dmytruk — APPROVED** [review]
Nice!

**Comment by yawkat** [comment]
@n0tl3ss seems that the OciLoggingSpec is failing *again*. "Error returned by CreateLogGroup operation in LoggingManagement service.(400, LimitExceeded, false) The following service limits were exceeded: log-group-count. Request a service limit increase from the service limits page in the console."

I can see that our tenancy is indeed at that limit in us-ashburn-1. I wasn't able to find the offending log groups though, maybe there's some test that isnt cleaning them up after creation? We could also maybe use another region.

**Comment by n0tl3ss** [comment]
The issue was caused because over time some stale resources (logs, logs group) accumulated probably when something fails and the cleanup hasn't been run. I have added cleanup at the end of the tests that will try to clean all log groups that name starts with `micronaut_test_` and resource was created before 24h from the test run. That should prevent accidentally deletion of another log group if multiple builds/tests are run in parallel.

**Comment by yawkat** [comment]
Thanks!

**Pull request merged**
